### ISSUE TITLE
Write the analysis

### ISSUE THREAD

**Issue by cruzzan** [cruzzan/git-ui-thesis#14]
- A small section for RQ1 and RQ2
- A section for RQ3 and RQ4
  Here we will want to talk about the following:
- A section for RQ5 with diagrams and references to the interviews and ui analysis, this will answer the question as close as we will be able to get. We most will probably not be able to determine anything solid because the question is very wide.
  Here we will need to talk about:
  - The trend in users swapping interfaces
  - The word association at different levels
  - How the intel from the interviews plays in 
  - How much issues the gui users have compared to cli users
  - What has been found in RQ3 and RQ4
  - Why the different demographics use what they use (One for CLI, One for GUI)
  - How the operating system seems to play into the choise regardless of demographic
  - How what they use git for plays into the choise regardless of demographic

Probably more stuff later.

**Comment by RobinOlofsson** [comment]
RQ1-RQ4: Done

**Comment by RobinOlofsson** [comment]
Renskrivning ska göras, men tar inte med det i denna issuen. Stänger denna.
