### ISSUE TITLE
Chapter 3 - Research methodology, 3.4.1 Survey -> Crafting and distrubition

### ISSUE THREAD

**Issue by RobinOlofsson** [cruzzan/git-ui-thesis#42]
Add a reference to snowballing

**Comment by cruzzan** [comment]
Förstår inte exakt vad du menar med snowballing här? Det borde väl vara under literaturstudien?

**Comment by RobinOlofsson** [comment]
Nae, enligt Conny så använde vi någon form av snowballing när vi distribuerade. Kanske missförstod.

On Mon, Aug 10, 2015 at 1:59 PM -0700, "Sebastian Hultstrand" notifications@github.com wrote:
Förstår inte exakt vad du menar med snowballing här? Det borde väl vara under literaturstudien?

---
