### ISSUE TITLE
Remove the UI analisys content

### ISSUE THREAD

**Issue by cruzzan** [cruzzan/git-ui-thesis#47]
This is cut becouse of the trouble we are haveing finding a way to treat this objectively and not have to defend a vey flawed way of gathering the information.

All the content that has to do with the UI Analisys needs to go.

**Comment by cruzzan** [comment]
Jag kom till rad 166 än så länge. Så börja där om du ska kika mer på detta idag :) @RobinOlofsson

**Comment by RobinOlofsson** [comment]
Borde vara helt borta nu, har kommenterat ut det som var i tabellen osv. Kunde inte hitta något mer så stänger issuen så får vi se om vi hittar något mer när vi renskriver sen. @cruzzan
