### ISSUE TITLE
Extend the analisys

### ISSUE THREAD

**Issue by cruzzan** [cruzzan/git-ui-thesis#5]
Write more about HOW the questions will be analysed.

**Comment by cruzzan** [comment]
@RobinOlofsson du kan gärna få läsa igenom det vi har där nu och säga om det verkar vettigt eller om vi behöver fylla på ännu mer.

**Comment by RobinOlofsson** [comment]
Verkar definitivt vettigt, kan inte komma på något mer som jag skulle vilja ha in just nu iallafall. Känns som att vi har fått med det viktigaste.

**Comment by cruzzan** [comment]
Ait, då tar vi och stänger denna for now @RobinOlofsson

**Comment by RobinOlofsson** [comment]
Gör så!

```
    Skickat från Outlook för Android

_____________________________
```

Från:Sebastian Hultstrand

Ämne:Re: [git-ui-thesis] Extend the analisys (#5)

Till:, cruzzan/git-ui-thesis

Kopia:, RobinOlofsson

Ait, då tar vi och stänger denna for now @RobinOlofsson
