### ISSUE TITLE
Who took part in the survey? - Introduction

### ISSUE THREAD

**Issue by RobinOlofsson** [cruzzan/git-ui-thesis#53]
"... through an online service, that has been sent out to developers within the industry" 

It should be clear about who took part in the survey. If the companies would like to be anonymous that's fine but who are they and what do they do.
Technology company? Developers? And where are they located? It could have an impact on the survey.
Because this is thesis is based on interviews and surveys, it is not possible to recreate it exactly the same.
But if you were to be more detailed about what kind of people answered the survey it would help any future works that are based on this thesis. Now they will not be able to find what kinds of people answered the survey

**Comment by cruzzan** [comment]
Jag uppdaterar och tar bort referenser till företag, eftersom att vi inte faktiskt har haft kontakt med organisationer utan individer som sedan hjälpt oss sprida vidare surveyn.

**Comment by RobinOlofsson** [comment]
Ok!

On Sun, Sep 6, 2015 at 6:55 AM -0700, "Sebastian Hultstrand" notifications@github.com wrote:
Jag uppdaterar och tar bort referenser till företag, eftersom att vi inte faktiskt har haft kontakt med organisationer utan individer som sedan hjälpt oss sprida vidare surveyn.

---
