### ISSUE TITLE
Include results?

### ISSUE THREAD

**Issue by RobinOlofsson** [cruzzan/git-ui-thesis#54]
"The results of the literature study gave
us clues about which UI we could expect to be more prefered amongst Git users
and why." -  Results should not be included here

**Comment by cruzzan** [comment]
Jag förstår inte riktigt vad som önskas här @RobinOlofsson

**Comment by RobinOlofsson** [comment]
Jag tror han menar vi inte ska ha med den meningen där. Att vi inte ska diskutera resultat där liksom.

On Sun, Sep 6, 2015 at 7:00 AM -0700, "Sebastian Hultstrand" notifications@github.com wrote:
Jag förstår inte riktigt vad som önskas här @RobinOlofsson

---
