### ISSUE TITLE
"consensus on forums and message boards around the web"

### ISSUE THREAD

**Issue by RobinOlofsson** [cruzzan/git-ui-thesis#58]
"This at least seems to be the consensus on forums and message boards around the web, and it coincides quite accurately with our experiences as well."

Any references? You cannot say things like this without have any evidence to back it up.

**Comment by cruzzan** [comment]
Jag kan inte riktigt lägga några referenser till detta.... Det är ett fenomen som vi har kunnat observera men jag kan inte ge några exempel på rak arm... Plus att vi säger att det verkar som att det är så här, vi påstår inte direkt att det är så oavsett vad. Jag tror att vi låter den här vara.
