### ISSUE TITLE
Other comments

### ISSUE THREAD

**Issue by RobinOlofsson** [cruzzan/git-ui-thesis#65]
---
## 3.4.1 Survey - crafting and distribution

"The survey was made as a web form that we can easily collect the data from and most of all distribute easily. Distribution of the survey was done through a number of different channels such as BTH:s student mail list, contacts at different Swedish companies and finally 8 different sub-reddits (Forum boards at the popular web forum Reddit) associated with software development."
- Because it was online and also sent out to Swedish collage students it
  would have been interesting to see if there was any difference based on the users region/location
  The interviews was also with Swedes, it would have been interesting if someone was from another country and see if they had any differences in opinion.
  I assume you sent the survey to the whole school and therefore my other comment about asking the user if they know about git could cause problems here because there could be responers who do not know what Git is.

---
## 3.4.2 Interviews

"The interviews were conducted with a small group of subjects that were representative of the different demographics that answered the survey. The way that we determined a demographic in this context was the level of proficiency with Git that the subject indicates they had and how long the subject had been using Git for. "
- This like the survey could be confirmed by asking the interviewee questions about git to confirm their knowledge level

"There are no clear guidelines that we've followed in the creation of these groups,
it was based on common logic by us."
- Because there are no lines between what makes a user "Average" or "Pro" the distinction between group 1 and 2 is not clear. I think there could be users who think they are "Pro" but actually are "Average" and it is not discussed in this thesis about what could be done to clarify the which group that user belongs to. Maybe how many times the user has to ask for help could be used here to help the users find their correct group?

---
## 6. Analysis

"In collaborative work it's more common to use a graphical user interface than working with large scale version control with branch management and code review through Git."
- It is important to clarify if this is part of the discussion (a thought) or a fact

**Comment by RobinOlofsson** [comment]
@cruzzan Kolla gärna igenom detta, kom gärna med åsikter :)

**Comment by cruzzan** [comment]
Kikat men vet inte riktigt vad jag ska säga... ^^

**Comment by RobinOlofsson** [comment]
Slängde in dem i svarsdokumentet, men vi har nog redan svarat på dem nu. Ska fixa sista på analysen o sen stänger jag denna.
