### ISSUE TITLE
Fill in some stuff in the background

### ISSUE THREAD

**Issue by cruzzan** [cruzzan/git-ui-thesis#7]
- Add more info to the git section
- Add more info to the GUI v. CLI section

**Comment by cruzzan** [comment]
Git section should be about done. @RobinOlofsson could please read and review it.

**Comment by cruzzan** [comment]
Added more to the GUI v. CLI section @RobinOlofsson could you check it out and if you are good you can close this issue.

**Comment by RobinOlofsson** [comment]
Ser riktigt bra ut! Helnöjd!
